# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: MiniInventory
email: office@mikemitterer.at
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: "jekyll-miniinventory/" # the subpath of your site, e.g. /blog

# the base hostname & protocol for your site
# url: "http://127.0.0.1:4000"
url: "http://mikemitterer.github.io/"

twitter_username: jekyllrb
github_username:  jekyll

gems: ['jekyll-lunr-js-search']

lunr_search:
  excludes: [web/search, category ]

exclude: [ "ministock.iml", "README.txt" ]

defaults:
  -
    scope:
      path: "web"
      type: "pages"
    values:
      weight: 0
  -
    scope:
      path: "_posts/lagera"
      type: "posts"
    values:
      category: "lagera"

# Build settings
markdown: kramdown
